root: true
env:
  browser: true
  node: true
  vue/setup-compiler-macros: true

extends:
  - eslint:recommended
  - '@nuxt/eslint-config'
  - plugin:prettier/recommended

rules:
  sort-imports: error

overrides:
  - files: ["*.ts", "*.vue"]
    rules:
      "@typescript-eslint/explicit-function-return-type": error
