root: true
env:
  browser: true
  node: true
  vue/setup-compiler-macros: true

parser: 'vue-eslint-parser'

parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended

plugins:
  - vue

rules: {}

overrides:
  - files: ["*.ts", "*.js", "*.vue"]
    rules:
      "@typescript-eslint/explicit-function-return-type": error
