overrides:
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
  vite@>=6.2.0 <6.2.3: '>=6.2.3'
  vite@>=6.2.0 <6.2.4: '>=6.2.4'
  vite@>=6.2.0 <6.2.5: '>=6.2.5'
  vite@>=6.2.0 <6.2.6: '>=6.2.6'

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - esbuild
  - vue-demi
